### ISSUE TITLE
Man-less pihotspot.

### ISSUE THREAD

**Issue by reigelgallarde** [Kupiki/Kupiki-Hotspot-Portal#6]
Currently our pihotspot needs someone to create the login credentials and give it to the customer.

I'm thinking of going full automated.
Adding a coinslot and an numpad to the pi.

![image](https://user-images.githubusercontent.com/10612336/32941445-289bdc0e-cbc9-11e7-88ab-99f372c4d4f2.png)
![image](https://user-images.githubusercontent.com/10612336/32941473-4467ede2-cbc9-11e7-86e2-8b10f4b643f2.png)

With this, the customer just need to:

1. connect to the hotspot
2. insert coin
3. press the number found on the login screen
4. press the Authenticate button

I'm still in the middle of starting to code.
My problem now is how to make the communication between the pi and the correct device that inserted the coin.

I'm bringing this up for discussion, hoping to find help.

A sample login screen.
After pressing the correct number on the number pad, the server will send the login credentials and the grey button will turn to pink. 
Pressing the Authenticate button is the same as the Login button before. The username and password are hidden fields which is populated when coin is inserted.

![image](https://user-images.githubusercontent.com/10612336/32941847-8294ff32-cbca-11e7-89dd-e5b81c21b7eb.png)

**Comment by pihomeserver** [comment]
Another idea : 
- Press a key to start -> System is generating a disabled user XYZ (set it within the Disable group)
- Ask the guy to pay following your process
- If payment is done, activate the user by removing it from the group and add it in another group with a time or volume limit

This way you keep the authentication process and can split portal from payment system

Issue i see is if the guy pays twice he will get 2 different users
